# Generated by Django 4.1.4 on 2022-12-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_rename_age_truck_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("filter", models.BooleanField()),
                ("currentmiles", models.IntegerField()),
                ("services", models.TextField(max_length=300)),
                (
                    "weeklychecks",
                    models.CharField(
                        choices=[
                            ("T", "Tire Pressure"),
                            ("E", "Engine Oil Level"),
                            ("M", "Mirrors"),
                            ("L", "Lights"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.truck"
                    ),
                ),
            ],
        ),
    ]
