# Generated by Django 4.1.4 on 2022-12-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="currentmiles",
            field=models.IntegerField(verbose_name="Current Miles"),
        ),
        migrations.AlterField(
            model_name="service",
            name="date",
            field=models.DateField(verbose_name="Service Date"),
        ),
        migrations.AlterField(
            model_name="service",
            name="filter",
            field=models.BooleanField(verbose_name="Replaced Oil Filter?"),
        ),
        migrations.AlterField(
            model_name="service",
            name="services",
            field=models.TextField(max_length=300, verbose_name="Services Performed"),
        ),
        migrations.AlterField(
            model_name="service",
            name="weeklychecks",
            field=models.CharField(
                choices=[
                    ("T", "Tire Pressure"),
                    ("E", "Engine Oil Level"),
                    ("M", "Mirrors"),
                    ("L", "Lights"),
                ],
                default="T",
                max_length=1,
                verbose_name="Weekly Checks",
            ),
        ),
    ]
