# Generated by Django 4.1.4 on 2022-12-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_service_currentmiles_alter_service_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="service",
            name="currentmiles",
        ),
        migrations.RemoveField(
            model_name="service",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="service",
            name="services",
        ),
        migrations.AlterField(
            model_name="service",
            name="weeklychecks",
            field=models.CharField(
                choices=[
                    ("T", "Tire Pressure"),
                    ("E", "Engine Oil Level"),
                    ("M", "Mirrors"),
                    ("L", "Lights"),
                ],
                max_length=1,
                verbose_name="Weekly Checks",
            ),
        ),
    ]
