# Generated by Django 4.1.4 on 2022-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_service_options_remove_service_currentmiles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="service",
            name="weeklychecks",
            field=models.CharField(
                choices=[
                    ("T", "Tire Pressure"),
                    ("E", "Engine Oil Level"),
                    ("M", "Mirrors"),
                    ("L", "Lights"),
                ],
                default="T",
                max_length=1,
                verbose_name="Weekly Checks",
            ),
        ),
    ]
