# Generated by Django 4.1.4 on 2022-12-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_mod_alter_service_weeklychecks"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="mods",
            field=models.ManyToManyField(to="main_app.mod"),
        ),
    ]
