# Generated by Django 4.1.4 on 2022-12-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_rename_age_mod_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mod",
            name="skill",
            field=models.PositiveIntegerField(verbose_name="Difficulty to Install"),
        ),
    ]
